### ISSUE TITLE
Failing in `develop` Cypress pre-release

### ISSUE THREAD

**Issue by jennifer-shehane** [bahmutov/cypress-hyperapp-unit-test#250]
This app is failing when run through `develop` of `cypress` since the TypeScript Updates were merged in https://github.com/cypress-io/cypress/pull/5780

Failing CI: https://circleci.com/gh/cypress-io/cypress-test-example-repos/88750

<img width="1019" alt="Screen Shot 2020-03-23 at 12 48 07 PM" src="https://user-images.githubusercontent.com/1271364/77287703-95475c00-6d04-11ea-983c-5cc72190fe48.png">

**Comment by bahmutov** [comment]
I have upgraded TypeScript to v3.8.3 let's see what happens next

**Comment by jennifer-shehane** [comment]
Seems to be passing now https://circleci.com/gh/cypress-io/cypress-test-example-repos/89554

**Comment by bahmutov** [comment]
Yeah so updating typescript from v2 to v3 solves it
